### ISSUE TITLE
Create a function to compact ids

### ISSUE THREAD

**Issue by vijaybarve** [vijaybarve/taxotools#103]
If DwC data is used, it has ids provided by the service with their own ids. At times id provided by other data providers are non numeric or too large numbers. 

It will be useful for `taxotools` to compact these numbers and also convert them to numeric, so other functions like `merge_lists` do not fail.

**Comment by vijaybarve** [comment]
@Jegelewicz Try out this function

**Comment by Jegelewicz** [comment]
I get this

Error in rename_column(dat, id, "id_") : 
  could not find function "rename_column"
