### ISSUE TITLE
merge_lists should return single data frame

### ISSUE THREAD

**Issue by vijaybarve** [vijaybarve/taxotools#104]
Rather than returning list of up to three data frame, the function should return single data frame with a additional field `merge_tag` to tell the status of each name. The values of the `merge_tag` would be

- `orig` names in the master
- `add` checklist names that matched using synonym linkages including direct matches 
- `new` checklist names that did NOT match with master. Potentially new taxa.
- `multi` taxon from checklist for which two synonyms matched with two different accepted names in master

  and a parameter to control what all is returned. The options could be

- `all`  = `orig` + `add` + `new` + `multi`: all the data 
- `add` = `orig` + `add` : returns all records from master + matched records from checklist 
- `merged` = `orig` + `add` + `new` : returns all records from master + matched records from checklist + new taxon from checklist
- `new` returns only new taxon entities that did not match with master
- `multi` taxon from checklist for which two synonyms matched with two different accepted names in master

**Comment by vijaybarve** [comment]
@Jegelewicz @yanisica will this be useful or trouble?

**Comment by Jegelewicz** [comment]
I think it would be useful - keeping the data together is usually better than splitting it up so that stuff doesn't get lost.
