### ISSUE TITLE
taxo2doc sorting

### ISSUE THREAD

**Issue by Jegelewicz** [vijaybarve/taxotools#119]
Currently taxo2doc sorts by genus name. This presents results where families are all broken up:

![image](https://user-images.githubusercontent.com/5725767/119536374-40f39e00-bd46-11eb-8d0f-6cc3e92e6f53.png)

I think that it would be easier for review if the order was by family, then genus.

**Comment by vijaybarve** [comment]
Thanks @Jegelewicz, just noticed that too. I will post a fix soon.
