### ISSUE TITLE
list_higher_taxo() object 'inat' not found

### ISSUE THREAD

**Issue by SrishtiJ1305** [vijaybarve/taxotools#33]
I tried the example code for "list_higher_taxo" and here is the issue:
inat <- list_higher_taxo(inat)
**_Error in list_higher_taxo(inat) : object 'inat' not found_**

Session info ───────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_India.1252          
 ctype    English_India.1252          
 tz       Europe/Berlin               
 date     2020-01-18

taxotools    * 0.0.42   2020-01-19 [1] Github (vijaybarve/taxotools@16fd1a9)

**Comment by SrishtiJ1305** [comment]
Hi, I tried to use the example code for this function again but this time there was a different issue:
Error in which(colnames(indf) == canonical) : 
  argument "canonical" is missing, with no default.

**Comment by vijaybarve** [comment]
Can you please post the code with each issue @SrishtiJ1305

**Comment by SrishtiJ1305** [comment]
This issue came only with the old version.
