### ISSUE TITLE
match_lists() object 'master' not found

### ISSUE THREAD

**Issue by SrishtiJ1305** [vijaybarve/taxotools#34]
I tried the example code for "match_lists" and here is the issue: 
`master <- data.frame("canonical" = c("Abrothrix longipilis",
                                    "Acodon hirtus",
                                    "Akodon longipilis apta",
                                    "Akodon longipilis castaneus",
                                    "Chroeomys jelskii",
                                    "Acodon jelskii pyrrhotis"),
                    stringsAsFactors = F)
checklist <- data.frame("canonical" = c("Abrothrix longipilis",
                                    "Akodon longipilis apta",
                                    "Akodon longipilis castaneus",
                                    "Abrothrix jelskii",
                                    "Acodon jelskii pyrrhotis"),
                    stringsAsFactors = F)
match_lists(master,checklist,"canonical","canonical")`
**_Error in is.data.frame(x) : object 'master' not found_**
Session info ───────────────────────────────────────────────────────
setting value
version R version 3.6.2 (2019-12-12)
os Windows 10 x64
system x86_64, mingw32
ui RStudio
language (EN)
collate English_India.1252
ctype English_India.1252
tz Europe/Berlin
date 2020-01-18

taxotools    * 0.0.42   2020-01-19 [1] Github (vijaybarve/taxotools@16fd1a9)

**Comment by vijaybarve** [comment]
Please put relevant issue title, i.e. what function and what kind of error.

**Comment by vijaybarve** [comment]
In match_lists() v 0.0.42 I see following example code.
````
master <- data.frame("canonical" = c("Abrothrix longipilis",
                                    "Acodon hirtus",
                                    "Akodon longipilis apta",
                                    "Akodon longipilis castaneus",
                                    "Chroeomys jelskii",
                                    "Acodon jelskii pyrrhotis"),
                    stringsAsFactors = F)
checklist <- data.frame("canonical" = c("Abrothrix longipilis",
                                    "Akodon longipilis apta",
                                    "Akodon longipilis castaneus",
                                    "Abrothrix jelskii",
                                    "Acodon jelskii pyrrhotis"),
                    stringsAsFactors = F)
match_lists(master,checklist,"canonical","canonical")

````

**Comment by SrishtiJ1305** [comment]
It has been fixed and is not an issue anymore
